sudo: false
branches:
  only:
    - master
language: node_js
node_js:
  - "7"
cache:
  yarn: true
  directories:
    - node_modules
env:
  - JANUS_LOG_LEVEL=warn
before_script:
  - npm install codecov
after_success:
  - node node_modules/.bin/codecov
